main:
	gcc 1-ptrArgs.c -o ptr1
	gcc 2-arrayPtr.c -o ptr2
	gcc 3-findSmall.c -o ptr3
	gcc 4-ptrToFunction.c -o ptr4
debug:
	gcc 1-ptrArgs.c -g -o ptr1 -Wall
clean:
	rm -f ./ptr1
	rm -f ./ptr2
	rm -f ./ptr3
	rm -f ./ptr4